### ISSUE TITLE
Incorrect behavior when no Approach is Selected for a Skill Roll

### ISSUE THREAD

**Issue by calliban** [saethone/l5r5epro#1]
For any of the skills, if the Approach Dropdown Menu is set on "Select Approach", the roll template shows "Approach" as "none", but still uses the same number of Ring dice and roll template it was using for the previous roll.

Suggestion: Remove the "Select Approach" dropdown item with the Air Ring, as the game does not allow for Approach-less skill rolls.

![image](https://user-images.githubusercontent.com/4281621/62413801-c0e8cb00-b5e9-11e9-8761-a96d2676d082.png)

**Comment by saethone** [comment]
the way the sheet worker assigns the approaches to the roll requires that i have a blank option...but I did have an issue where unselecting your approach would just use the last one still. I went ahead and corrected that, so it won't color the header or apply the ring any longer. that way you can at least see that you forgot to select an approach

![image](https://user-images.githubusercontent.com/13894683/62419424-549bb500-b645-11e9-876c-eef3739486d8.png)
