### ISSUE TITLE
Changing sheet tabs makes the background image to be displaced

### ISSUE THREAD

**Issue by calliban** [saethone/l5r5epro#2]
The rice-paper background image is kinda displaced (reprojected?) whenever I click on certain options.

For instance, on the Player sheet, if I click on Narrative then Combat, the background image moves a bit.

This behaviour also appears whenever I click the "+Add" button on any listings, or whenever I click on something that changes the formatting (for instance, changing the technique type on the Techniques page).

**Comment by saethone** [comment]
apparently i had the background size set to automatically resize with the sheet. 

Changed it so that it's a set width, and will just repeat length-wise if needed
